## Deep Learning
* deep learning is more suited for image recognition, computer vision, natural language processing and understanding problems
* learning rate too high caused overfit and too small would have no impact
* must specify the loss function to use to evaluate a set of weights, the optimizer used to search through different weights for the network and any optional metrics we would like to colelct and report during training
* binary_corssentropy is the log loss 
* Adam: gradient descent algorithm 
* Early stopping allow trying for 3 times before it moves on to the next batch

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.utils import to_categorical 
#SGD Stochastic gradient decent optimizer
from keras.optimizers import SGD 
from keras.callbacks import EarlyStopping

input_shape=len(all_features)
print(input_shape)

# This creates a two-layer sequential NN model
def get_new_model(input_dim = input_shape):
    model = Sequential()
    model.add(Dense(100, input_dim = input_shape, activation='relu'))
    model.add(Dropout(0.2)) 
    model.add(Dense(100, activation='relu'))
    model.add(Dropout(0.2)) 
    model.add(Dense(2, activation='softmax'))
    return(model)

#lr_to_test=[.00001, .0001,0.01, 1]
#lr_to_test=[0.009, 0.02, 0.03,0.04,0.05]
# compare model with low, medium and high learning rate
lr_to_test=[.01]
for lr in lr_to_test:
        print('\n\nTesting model with learning rate: %f\n'%lr )
        model = get_new_model()
        my_optimizer = SGD(lr=lr)
        model.compile(optimizer=my_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
        early_stopping_monitor = EarlyStopping(patience=3)
        model.fit(X, Y, epochs=50, validation_split=0.3, batch_size=100, callbacks=[early_stopping_monitor], verbose=False)

### Activation Functions

Activation function converts/transforms the input into a format that works better in the gradient descent process for machine learning:

https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6

#### sigmoid function
The sigmoid function converts the input in the range of (0,1). Use it for the output layer when performing binary forecast. 

**Formula**: a=sigmoid(z)=1/(1+e(-z))

softmax function is a more generalized logistic activation function which is used for multiclass classification

#### tanh

tanh function is a shifted sigmoid function, returns values in the range of (-1, 1)
it works better than sigmoid function by centering the data around 0 rather than 0.5

**Formula**:
a = tanh(z) = e(z) - e(-z)/(e(z) + e(-z))

<img src="images/sigmoid vs tanh.png">

#### ReLU

Your NN learns much faster with ReLU than with sigmoid/tanh. 

**Formula**: a=max(0,z)
    
<img src="images/sigmoid vs relu.png">



#### Activation Cheat Sheet

<img src="images/activation cheat sheet.png">

### Gradient Descent for NN

<img src="images/gradient descent for nn.jpg" >

In [1]:
import numpy as np

A = np.random.randn(4,3)

print(A)

[[ 0.35622124 -0.90113397 -0.42475039]
 [-0.00492433  0.01713343  1.1135313 ]
 [ 3.1632273   0.00556174  0.58684141]
 [-0.7251957  -0.72182714 -0.10614139]]


In [2]:
B = np.sum(A, axis=1, keepdims=True)
print(B)

[[-0.96966312]
 [ 1.1257404 ]
 [ 3.75563044]
 [-1.55316423]]


In [ ]:
grads["dA" + str(L)], grads["dW" + str(L)], grads["db" + str(L)] = linear_backward(sigmoid_backward(dAL, 
                                                                                    current_cache[1]), 
                                                                                       current_cache[0])
