### Vectorization

In [1]:
import numpy as np
import pandas as pd

In [11]:
import catboost

In [12]:
print(catboost.__version__)

0.9.1.1


##### numpy.random.rand: Create an array of the given shape and propagate it with random samples from a uniform distribution over [0, 1). The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.

In [15]:
np.random.seed(1)
t = np.random.rand(3,1)
print(t)

[[4.17022005e-01]
 [7.20324493e-01]
 [1.14374817e-04]]


In [18]:
x = np.random.randn(3,1)
print(x)

[[-1.01701414]
 [ 0.63736181]
 [-0.85990661]]


##### np.random.randn return a sample (or samples) from the “standard normal” distribution.

In [23]:
w = np.random.randn(1,3)
print(w)

[[ 0.56434487 -0.56651023  0.7299756 ]]


In [10]:
w = np.random.randn(3,1)
print(w.shape)
print(w.T.shape)

(3, 1)
(1, 3)


In [12]:
x = np.array([[-1.01701414],
 [ 0.63736181],
 [-0.85990661]])

# w = np.random.randn(1,3)
w = np.array([[ 1.77260763, -1.11036305,  0.18121427]])
print(x.shape, w.shape)
result_matmul = np.matmul(w, x)
print(result_matmul)

(3, 1) (1, 3)
[[-2.66629738]]


In [28]:
np.dot(w,x)

array([[-2.66629738]])

##### numpy.dot() This function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication. For 1-D arrays, it is the inner product of the vectors. np.matmul produces the same output. 

In [7]:
z = np.dot(w,x)
print(z)

[[-2.66629738]]


In [9]:
# For matrix mutiplication, the shape must be aligned 
z = np.dot(w.T,x)
print(z)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

##### numpy.multiply returns element-wise multiplication

In [13]:
# np.multiply can create an outer product 
x = np.random.randn(3,1)
w = np.random.randn(1,3)
print(x)
print(w)
z = np.multiply(w, x)
# z2 = np.matmul(w, x)
print(z)
# print(z2)

[[-0.44540123]
 [-0.23062995]
 [-0.66449726]]
[[ 0.6395342  -0.29798608  0.83942743]]
[[-0.28484932  0.13272337 -0.37388201]
 [-0.14749574  0.06872451 -0.19359711]
 [-0.42496872  0.19801093 -0.55779723]]


In [15]:
z2 = np.outer(w,x)
print(z2)

[[-0.28484932 -0.14749574 -0.42496872]
 [ 0.13272337  0.06872451  0.19801093]
 [-0.37388201 -0.19359711 -0.55779723]]


In [64]:
x = np.random.randn(3,1)
w = np.random.randn(3,1)
print('x', x)
print('w', w)
z = np.multiply(w, x)
# z2 = np.matmul(w, x)
print('z', z)
# print(z2)

x [[-0.30817074]
 [ 0.36583834]
 [ 1.60750704]]
w [[-0.23817737]
 [-0.34082828]
 [ 0.48759421]]
z [[ 0.0733993 ]
 [-0.12468805]
 [ 0.78381112]]


In [65]:
x = np.random.randn(3,1)
w = np.random.randn(3,1)
print('x', x)
print('w', w)
z = np.matmul(w, x)
# z2 = np.matmul(w, x)
print('z', z)
# print(z2)

x [[1.73907303]
 [0.0689698 ]
 [0.47324139]]
w [[-0.65035502]
 [-0.77910696]
 [-0.77766271]]


ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [66]:
x = np.random.randn(3,1)
w = np.random.randn(1,3)
print('x', x)
print('w', w)
z = np.matmul(w, x)
# z2 = np.matmul(w, x)
print('z', z)
# print(z2)

x [[0.6225628 ]
 [0.42756207]
 [0.0740096 ]]
w [[-0.4531686   0.60415364  2.38520581]]
z [[0.1527154]]


In [35]:
np.sum(z)

1.5581687049894266

In [2]:
a = np.random.randn(1,4)
Y = np.random.randn(1,4)
print(a)
print(Y)

[[-1.81816225 -0.20965202 -0.03282992  1.17068988]]
[[ 1.3202     -1.01317285 -1.02271485  1.10778758]]


In [3]:
np.multiply(a, Y)

array([[-2.4003378 ,  0.21241373,  0.03357565,  1.29687571]])

In [5]:
np.squeeze(np.sum(np.multiply(a, Y)))

-0.8574727148180479

In [10]:
# dZ2 = A2 - Y
# dW2 = (1/m)*np.dot(dZ2, A1.T)
    
dZ2 = np.random.randn(1,10)
A1 = np.random.randn(10,4)

dW2 = np.dot(dZ2, A1)
print(dW2)

[[ 0.21575967  0.08310098 -2.05476959 -3.11545857]]


#### Broadcasting

In [38]:
A = np.random.rand(3,4)
print(A)

[[0.89588622 0.42809119 0.96484005 0.6634415 ]
 [0.62169572 0.11474597 0.94948926 0.44991213]
 [0.57838961 0.4081368  0.23702698 0.90337952]]


In [39]:
cal = A.sum(axis=0)

array([2.09597155, 0.95097397, 2.15135629, 2.01673315])

In [40]:
a_100 = A + 100
print(a_100)

[[100.89588622 100.42809119 100.96484005 100.6634415 ]
 [100.62169572 100.11474597 100.94948926 100.44991213]
 [100.57838961 100.4081368  100.23702698 100.90337952]]


In [51]:
b = np.array([[100, 200, 300, 400]])
print(b)
print(A.shape)
print(b.shape)

[[100 200 300 400]]
(3, 4)
(1, 4)


In [49]:
c = A + b 
print(c)

[[100.89588622 200.42809119 300.96484005 400.6634415 ]
 [100.62169572 200.11474597 300.94948926 400.44991213]
 [100.57838961 200.4081368  300.23702698 400.90337952]]


In [53]:
d = np.random.randn(3,1)
print(d)
print(A)

[[ 0.07083664]
 [ 0.71758983]
 [-0.25070491]]
[[0.89588622 0.42809119 0.96484005 0.6634415 ]
 [0.62169572 0.11474597 0.94948926 0.44991213]
 [0.57838961 0.4081368  0.23702698 0.90337952]]


In [55]:
E = A + d
print(E)

[[ 0.96672286  0.49892783  1.03567669  0.73427814]
 [ 1.33928555  0.8323358   1.66707908  1.16750196]
 [ 0.3276847   0.15743189 -0.01367793  0.65267461]]


In [57]:
F = A + b
print(F)

[[100.89588622 200.42809119 300.96484005 400.6634415 ]
 [100.62169572 200.11474597 300.94948926 400.44991213]
 [100.57838961 200.4081368  300.23702698 400.90337952]]


In [60]:
# should avoid rank 1 array
a = np.random.randn(5)
print('rank 1 array:', a)
print(a.shape)

rank 1 array: [ 0.58192518 -0.41020752  2.2968661   1.68849705  0.62581147]
(5,)


In [62]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms


In [3]:
A = np.random.randn(1,5)
print(A)

[[ 0.3271142  -1.50259732 -0.62150583  2.35671931  1.36042912]]


In [5]:
# That's how you refer to the element in the array 
A[0,1]

-1.502597318939316